- name: Install Apache and MariaDB and Configures UFW
  hosts: ubuntu
  become: yes
  vars:
    db_root_password: "hopefully-a-secure-password"

  tasks:

    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: full
        autoremove: yes

    - name: Allow HTTP and HTTPS in UFW
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 80
        - 443

    - name: Install required Python MySQL package
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: Install Apache and MariaDB
      apt:
        name:
          - apache2
          - mariadb-server
          - mariadb-client
          - php
          - php-mysql
        state: present

    - name: Ensure MariaDB is running and enabled
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Secure MariaDB Installation (Set Root Password)
      mysql_user:
        name: root
        host: localhost
        password: "{{ db_root_password }}"
        check_implicit_admin: yes
        login_unix_socket: /var/run/mysqld/mysqld.sock
        priv: "*.*:ALL,GRANT"
