---
- name: Disable iptables for Docker Networks
  hosts: ubuntu
  become: yes
  tasks:
    - name: Copy content to /etc/docker/daemon.json
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
             "iptables": false
          }
      notify: Restart Docker

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
