---
- name: Ansible Playbook to copy new firmware file to Cisco switch or router
  hosts: cisco
  gather_facts: false
  vars:
    image_file: "/path/to/cisco.bin"
    image: "cisco.bin"
    ssh_user: "user"
    ssh_pass_file: "/path/to/password"
  tasks:
    - name: Enables ip scp server
      ios_config:
        lines:
          - ip scp server enable

    - name: Copies the image from Ansible host to Cisco switch or router
      delegate_to: localhost
      command: >
        sshpass -f {{ ssh_pass_file }} scp -O {{ image_file }} {{ ssh_user }}@{{ ansible_host }}:{{ image }}
      vars:
        ansible_command_timeout: 900
        ansible_ssh_timeout: 900

    - name: IOS Command to show directory
      ios_command:
        commands: dir
      register: dir_out

    - name: Verify bin file in directory
      assert:
        that: "'{{ image }}' in dir_out.stdout[0]"
        fail_msg: "Image not found in flash"

    - name: Disables ip scp server
      ios_config:
        lines:
          - no ip scp server enable
