---
- name: Change the Hostname of a Cisco Switch to Ansible Inventory Hostname
  hosts: cisco
  gather_facts: false
  
  tasks:
    - name: Set hostname
      ios_config:
        lines:
          - hostname {{ inventory_hostname }}
