---
- name: Configure the time on Cisco Switches
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Set the time server, timezone, and daylight savings
      cisco.ios.ios_config:
        lines:
          - ntp server x.x.x.x
          - clock timezone CST -6 0
          - clock summer-time CDT recurring 2 Sun Mar 2:00 1 Sun Nov 2:00

    - name: Save running-config to startup-config
      cisco.ios.ios_config:
        save_when: always
