- name: Backup running-config of Cisco Switches
  hosts: cisco
  gather_facts: false
    
  tasks:
    - name: Save config to file
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.txt"
          dir_path: "/ciscobackups"
