---
- name: Ansible Playbook to copy new firmware file to Cisco switch or router
  hosts: cisco
  gather_facts: false
  vars:
    image_file: "/path/to/cisco.bin"
    image: "cisco.bin"
    ssh_user: "user"
    ssh_pass_file: "/path/to/password"
  tasks:
    - name: Enables ip scp server
      ios_config:
        lines:
          - ip scp server enable

    - name: Pause for 15 seconds for SCP server to start
      pause:
        seconds: 15

    - name: Gather CURRENT boot info
      ios_command:
        commands:
          - show boot
      register: bootinfo

    - name: Extracts CURRENT bin file
      set_fact:
        boot_bin: "{{ bootinfo.stdout[0] | regex_search('flash[:/][^ ]+\\.bin') | regex_replace('^flash[:/]', '') }}"

    - name: Show extracted CURRENT bin file
      debug:
        var: boot_bin

    - name: Copy NEW bin file from Ansible host to Cisco switch or router
      delegate_to: localhost
      command: >
        sshpass -f {{ ssh_pass_file }} scp -O {{ image_file }} {{ ssh_user }}@{{ ansible_host }}:{{ image }}
      vars:
        ansible_command_timeout: 900
        ansible_ssh_timeout: 900

    - name: IOS Command to show directory
      ios_command:
        commands: dir
      register: dir_out

    - name: Verify NEW bin file in directory
      assert:
        that: "'{{ image }}' in dir_out.stdout[0]"
        fail_msg: "Image not found in flash"

    - name: Disables ip scp server
      ios_config:
        lines:
          - no ip scp server enable

    - name: Configure NEW boot path and SAVES configuration
      ios_config:
        lines:
          - boot system flash:{{  image }}
        save_when: always

    - name: IOS command to show boot variables
      ios_command:
        commands: show boot
      register: boot_out

    - name: Verify NEW bin file in boot variables
      assert:
        that: "'{{ image }}' in boot_out.stdout[0]"
        fail_msg: "Image not found in boot"

    - name: Reloads switch
      ios_command:
        commands:
          - command: "reload"
            prompt: "[confirm]"
            answer: "\r"

#    - name: Reload the switch
#      ansible.netcommon.cli_command:
#        command: "reload"
#        prompt: "[confirm]"
#        answer: "\r"

