---
- name: Ansible Playbook to copy new firmware file to Cisco switch or router
  hosts: cisco
  gather_facts: false
  vars:
    image_file: "/path/to/cisco.bin"
    image: "cisco.bin"
    ssh_user: "user"
    ssh_pass_file: "/path/to/password"
  tasks:
    - name: Enables the SCP server
      ios_config:
        lines:
          - ip scp server enable

    - name: Pause 30 seconds for SCP server to start
      pause:
        seconds: 30

    - name: Gathers the CURRENT boot info to variable
      ios_command:
        commands:
          - show boot
      register: bootinfo

    - name: Extracts the CURRENT bin file
      set_fact:
        boot_bin: "{{ bootinfo.stdout[0] | regex_search('flash[:/][^ ]+\\.bin') | regex_replace('^flash[:/]', '') }}"

    - name: Display the CURRENT bin file
      debug:
        var: boot_bin

    - name: Copies NEW image from Ansible host to Cisco switch
      delegate_to: localhost
      command: >
        sshpass -f {{ ssh_pass_file }} scp -O {{ image_file }} {{ ssh_user }}@{{ ansible_host }}:{{ image }}
      vars:
        ansible_command_timeout: 900
        ansible_ssh_timeout: 900

    - name: Show directory into variable
      ios_command:
        commands: dir
      register: dir_out

    - name: Verify NEW image was copied into the flash dir
      assert:
        that: "'{{ image }}' in dir_out.stdout[0]"
        fail_msg: "Image not found in flash"

    - name: Disables the SCP server
      ios_config:
        lines:
          - no ip scp server enable

    - name: Configure NEW boot path and saves configuration
      ios_config:
        lines:
          - boot system flash:{{ image }}
        save_when: always

    - name: Show boot info  into a variable
      ios_command:
        commands: show boot
      register: boot_out

    - name: Verify NEW bin file in boot path
      assert:
        that: "'{{ image }}' in boot_out.stdout[0]"
        fail_msg: "Image not found in the boot path"

    - name: Reloads the switch
      ios_command:
        commands:
          - command: "reload"
            prompt: "[confirm]"
            answer: "\r"
      vars:
        ansible_command_timeout: 30

   - name: Wait for the switch to RETURN
     wait_for:
       host: "{{ inventory_hostname }}"
       port: 22
       delay: 60
       timeout: 900
     delegate_to: localhost

   - name: Removes OLD image from switch
     ios_command:
       commands:
         - command: delete /force flash:{{ boot_bin }}
       save_when: always
