---
- name: Get model of ALL Cisco switches
  hosts: cisco
  gather_facts: false

  tasks:
    - name: Get show version
      ios_command:
       commands: show version | i cisco
      register: version

    - name: Save config to version folder
      copy:
       content: "{{ version.stdout[0] }}"
       dest: "/ciscobackups/{{inventory_hostname}}_model.txt"
