---
- name: Cisco IOS XE L2S Cat 1 STIG
  hosts: cisco
  gather_facts: false
  tasks:
    - name: V-220649 - Cisco switch must uniquely identify and authenticate all network-connected endpoint devices before establishing any connection.
      ios_config:
        lines:
          - radius server RADIUS
          - address ipv4 x.x.x.x
          - key SECURE_PASSWORD
          - exit
          - radius server RADIUS_2
          - address ipv4 y.y.y.y
          - key SECURE_PASSWORD
          - exit
          - aaa new-model
          - aaa group server radius RADIUS_SERVERS
          - server name RADIUS
          - server name RADIUS_2
          - exit
          - aaa authentication dot1x default group RADIUS_SERVERS
          - dot1x system-auth-control
