---
- name: Cisco IOS XE L2S Cat 3 STIG
  hosts: cisco
  gather_facts: false
  tasks:
    - name: V-220673 - Cisco switch must not have any switchports assigned to the native VLAN.
      ios_config:
        lines:
          - int range g0/1-10
          - switchport access vlan 20
          - exit
    - name: V-220663 - Cisco switch must have IGMP or MLD Snooping configured on all VLANs.
      ios_config:
        lines:
          - ip igmp snooping
    - name: V-220662 - Cisco switch must have Storm Control configured on all host-facing switchports.
      ios_config:
        lines:
          - int range g0/1-10
          - storm-control unicast bps 62000000
          - storm-control broadcast level bps 20000000
    - name: V-220655 - Cisco switch must have Root Guard enabled on all switch ports connecting to access layer switches.
      ios_config:
        lines:
          - int g0/12
          - spanning-tree guard root
          - exit
