---
- name: Move daily backup folders into a main folder
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Set fact for date variable Year-Month
      set_fact:
        date_folder: "{{ lookup('pipe', 'date +%Y-%B') }}"

    - name: Set fact for backup folder variable
      set_fact:
        backup_folder: "{{ lookup('pipe', 'date +%Y-%m') }}"

    - name: Creates Year-Month folder
      file:
        path: "/opt/backups/{{ date_folder }}"
        state: directory
        mode: '0775'
        group: 'group'
        owner: 'user'

    - name: Find all daily backup folders for current month
      ansible.builtin.find:
        paths: "/opt/ansible/backups"
        file_type: directory
        patterns: "{{ backup_folder }}-*"
      register: daily_folders

    - name: Move each daily backup folder into Month-Year folder
      command: mv "{{ item.path }}" "/opt/backups/{{ date_folder }}/"
      loop: "{{ daily_folders.files }}"
