---
- name: Move backup folders into a Main folder
  hosts: localhost
  gather_facts: false
  vars:
    user: "username"
  vars_prompt:
    - name: date_folder
      prompt: Enter the month and year of the folder
      private: false
    - name: backup_folder
      prompt: Enter the format of the backup folder (ex. 2025-09)
      private: false
  tasks:
    - name: Creates the Month-Year folder for access group
      file:
        path: "/path/to/folder/{{ date_folder }}"
        state: directory
        mode: '0755'
        group: '{{ user }}'
        owner: ''{{ user }}'

    - name: Find all daily backup folders for current month
      find:
        paths: "/path/to/folder"
        file_type: directory
        patterns: "{{ backup_folder }}-*"
      register: daily_folders

    - name: Move each daily folder into Month-Year folder
      command: mv "{{ item.path }}" "/path/to/folder/{{ date_folder }}/"
      loop: "{{ daily_folders.files }}"
